language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk6
install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Dgpg.skip=true
before_install:
 - sudo apt-get update
 - sudo apt-get install golang
script: 
 - go run make.go --test
