os:
  - linux
language: java
jdk:
  - oraclejdk8
env:
  - GOPATH="/tmp" GAUGE_ROOT="/tmp/gauge"
before_install:
  - sudo apt-get update
  - sudo apt-get install golang
  - go get github.com/tools/godep
install:
  - go run make.go
script: 
  - go run make.go --install
  - go get -d -u -v github.com/getgauge/gauge
  - cd $GOPATH/src/github.com/getgauge/gauge
  - godep restore
  - echo "gauge_repository_url = https://raw.githubusercontent.com/getgauge/gauge-nightly-repository/master/" >> skel/gauge.properties
  - go run build/make.go
  - go run build/make.go --install --prefix=$GAUGE_ROOT
  - cd ..
  - git clone --depth=1 https://github.com/getgauge/gauge-tests
  - cd gauge-tests
  - $GAUGE_ROOT/bin/gauge --install-all
  - TAGS="!unimplemented" ./starttests.sh java